### ISSUE TITLE
Packaging for Alpine Linux - soname symlink patch

### ISSUE THREAD

**Issue by sodface** [tari01/libodiosacd#3]
Hello, I recently [packaged libodiosacd ](https://pkgs.alpinelinux.org/packages?name=libodiosacd&branch=edge) for Alpine and I used the below patch to change the way the soname and symlink are handled:

```
--- ./Makefile.orig
+++ ./Makefile
@@ -33,7 +33,7 @@
 reader/dff: reader/dff.c; $(CC) -c $(CFLAGS) $^ -o $(VPATH)/$@.o
 reader/dsf: reader/dsf.c; $(CC) -c $(CFLAGS) $^ -o $(VPATH)/$@.o
 libodiosacd: libodiosacd.c; $(CC) -c $(CFLAGS) $^ -o $(VPATH)/$@.o
-odio-libsacd: $(foreach object, $(OBJECTS), $(VPATH)/$(object).o); $(CC) -o data/usr/lib/libodiosacd.so $^ $(LDFLAGS)
+odio-libsacd: $(foreach object, $(OBJECTS), $(VPATH)/$(object).o); $(CC) -o data/usr/lib/libodiosacd.so.1 $^ $(LDFLAGS)
 
 clean:
 
@@ -42,8 +42,8 @@
 
 install:
 
-	$(shell install -Dt $(DESTDIR)/usr/$(LIBDIR) ./data/usr/lib/libodiosacd.so)
-	$(shell ln -sf ./libodiosacd.so $(DESTDIR)/usr/$(LIBDIR)/libodiosacd.so.1)
+	$(shell install -Dt $(DESTDIR)/usr/$(LIBDIR) ./data/usr/lib/libodiosacd.so.1)
+	$(shell ln -sf ./libodiosacd.so.1 $(DESTDIR)/usr/$(LIBDIR)/libodiosacd.so)
 	$(shell install -Dt $(DESTDIR)/usr/include/libodiosacd ./src/libodiosacd.h)
 	$(shell install -Dt $(DESTDIR)/usr/include/libodiosacd/reader ./src/reader/disc.h)
 	$(shell install -Dt $(DESTDIR)/usr/include/libodiosacd/reader ./src/reader/media.h)
```

One of the Alpine developers [explains here](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=49232):

> Many Linux distributions (e.g. Alpine Linux and Debian) split packages
into multiple subpackages. For instance, library development headers are
usually separated from .so files since the former are commonly not
needed as a run-time dependency. As part of this split, only versioned
sonames are commonly provided by library packages (e.g.
libexample.so.4.2.0), the symbolic link to the current .so (e.g.
libexample.so -> libexample.so.4.2.0) is provided in a separate
development subpackage for every library. This is done to ensure that
the unversioned .so symbolic link is only used during compilation, for
loading purposes a versioned .so name should always be used. This eases
rebuilding packages on ABI changes (i.e. soname version bumps).

Would you consider making the above change so I can remove the downstream patch? I'm not sure what side effects this might have outside of Alpine.

**Comment by tari01** [comment]
@sodface 

Thanks for pointing this out. I have integrated your changes. It should not affect any linked projects.
Fixed via https://github.com/tari01/libodiosacd/commit/42c3c1db6aac4e2637f14d4c2a62c9ae43e14df5.
