### ISSUE TITLE
Documenting coefficients in filtersetup.c

### ISSUE THREAD

**Issue by plstonge** [tari01/libodiosacd#5]
Hello,

In [filtersetup.c](https://github.com/tari01/libodiosacd/blob/master/src/converter/filtersetup.c#L24), how those coefficients were made? I know it is close to a scaled [sinc()](https://mathworld.wolfram.com/SincFunction.html) function, but it is not exactly that for `FILTER18COEFS` and `FILTER116COEFS`. Can you put some comments about those coefficients?

Thank you.

**Comment by tari01** [comment]
@plstonge:

I stole the filter coefficients from Maxim V. Anisiutkin's FooBar2000 SACD [plugin](https://sourceforge.net/projects/sacddecoder/files/foo_input_sacd/). You can find the original listing in the `DSDPCMConstants.h` file. Unfortunately, no comments exist in there, either...

**Comment by plstonge** [comment]
Hello @tari01,

Thank you for the information. I will try to reverse-engineer these constants, or find a paper that describes the overall algorithm.

Have a nice day!

**Comment by tari01** [comment]
Closing as answered...
